# Generated by Django 3.1.1 on 2020-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20201024_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myimg',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
    ]
