# Generated by Django 3.1.3 on 2020-12-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('examcenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.examcenter')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
            bases=('app1.examcenter',),
        ),
    ]
